### PR TITLE
#164792998 Update Readme to carry basic details about the app.

### PR DESCRIPTION
**Pull request by NedyUdombat**
#### What does this PR do?
Updates Readme file to carry basic details about the application.

#### Description of Task to be completed?
Update readme file:
  * to contain a short description about the application
  * to contain api versioning guides
  * to contain api specs ( request body and response body)
  * to contain list of all endpoints

#### How should this be manually tested?
* clone `https://github.com/NedyUdombat/Role-Assigner.git`
* checkout to  a new branch = `ch-update-readme-164792998`
* pull from the remote branch to update the local branch
* open `README.md` file with any markdown preview tool at your disposal.

#### Any background context you want to provide?
Update to the readme will be regular as the development process progresses

#### What are the relevant pivotal tracker stories?
#164792998

#### Screenshots (if appropriate)
Screenshot 2019-03-21 at 8 04 58 AM

#### Questions:
None.

### CODE REVIEW

**Review by eben-k — APPROVED** [review]

**Comment by emmsdan** [comment]
I believe it would be better if the URL for the team should follow a more direct pattern that users can easily remember.
i.e. 
**POST**: `/api/v1/team/member` to create new member
**GET**: `/api/v1/team/members` to get members

**Comment by musonant** [comment]
Is it necessary to separate the endpoints for creating team-lead and QA separately?

**Comment by NedyUdombat** [comment]
> Is it necessary to separate the endpoints for creating team-lead and QA separately?

Yes, because they are two separate endpoints, they give two different responses

**Comment by NedyUdombat** [comment]
> I believe it would be better if the URL for the team should follow a more direct pattern that users can easily remember.
> i.e.
> **POST**: `/api/v1/team/member` to create new member
> **GET**: `/api/v1/team/members` to get members

Thank you  @emmsdan, I will rectify this

**Pull request merged**
